
services:
  dongguatv:
    build: .
    container_name: dongguatv
    restart: unless-stopped
    ports:
    - "3000:3000"
    environment:
    #- PORT=3000
    - TMDB_API_KEY=29c77d08ccf149f78deab9621898bb4c
    - ADMIN_PASSWORD=admin
